//// Generated by https://quicktype.io

//namespace hello_rusy.Data
//{
//    using System;
//    using System.Collections.Generic;

//    using System.Globalization;
//    using System.Text.Json;
//    using System.Text.Json.Serialization;

//    public partial class VideoIndexerResultClass
//    {
//        [JsonPropertyName("partition")]
//        public object Partition { get; set; }

//        [JsonPropertyName("description")]
//        public object Description { get; set; }

//        [JsonPropertyName("privacyMode")]
//        public string PrivacyMode { get; set; }

//        [JsonPropertyName("state")]
//        public string State { get; set; }

//        [JsonPropertyName("accountId")]
//        public Guid AccountId { get; set; }

//        [JsonPropertyName("id")]
//        public string Id { get; set; }

//        [JsonPropertyName("name")]
//        public string Name { get; set; }

//        [JsonPropertyName("userName")]
//        public string UserName { get; set; }

//        [JsonPropertyName("created")]
//        public DateTimeOffset Created { get; set; }

//        [JsonPropertyName("isOwned")]
//        public bool IsOwned { get; set; }

//        [JsonPropertyName("isEditable")]
//        public bool IsEditable { get; set; }

//        [JsonPropertyName("isBase")]
//        public bool IsBase { get; set; }

//        [JsonPropertyName("durationInSeconds")]
//        public long DurationInSeconds { get; set; }

//        [JsonPropertyName("duration")]
//        public string Duration { get; set; }

//        [JsonPropertyName("summarizedInsights")]
//        public object SummarizedInsights { get; set; }

//        [JsonPropertyName("videos")]
//        public Video[] Videos { get; set; }

//        [JsonPropertyName("videosRanges")]
//        public VideosRange[] VideosRanges { get; set; }
//    }

//    public partial class Video
//    {
//        [JsonPropertyName("accountId")]
//        public Guid AccountId { get; set; }

//        [JsonPropertyName("id")]
//        public string Id { get; set; }

//        [JsonPropertyName("state")]
//        public string State { get; set; }

//        [JsonPropertyName("moderationState")]
//        public string ModerationState { get; set; }

//        [JsonPropertyName("reviewState")]
//        public string ReviewState { get; set; }

//        [JsonPropertyName("privacyMode")]
//        public string PrivacyMode { get; set; }

//        [JsonPropertyName("processingProgress")]
//        public string ProcessingProgress { get; set; }

//        [JsonPropertyName("failureMessage")]
//        public string FailureMessage { get; set; }

//        [JsonPropertyName("externalId")]
//        public object ExternalId { get; set; }

//        [JsonPropertyName("externalUrl")]
//        public object ExternalUrl { get; set; }

//        [JsonPropertyName("metadata")]
//        public object Metadata { get; set; }

//        [JsonPropertyName("insights")]
//        public Insights Insights { get; set; }

//        [JsonPropertyName("thumbnailId")]
//        public Guid ThumbnailId { get; set; }

//        [JsonPropertyName("width")]
//        public long Width { get; set; }

//        [JsonPropertyName("height")]
//        public long Height { get; set; }

//        [JsonPropertyName("detectSourceLanguage")]
//        public bool DetectSourceLanguage { get; set; }

//        [JsonPropertyName("languageAutoDetectMode")]
//        public string LanguageAutoDetectMode { get; set; }

//        [JsonPropertyName("sourceLanguage")]
//        public Language SourceLanguage { get; set; }

//        [JsonPropertyName("sourceLanguages")]
//        public Language[] SourceLanguages { get; set; }

//        [JsonPropertyName("language")]
//        public Language Language { get; set; }

//        [JsonPropertyName("languages")]
//        public Language[] Languages { get; set; }

//        [JsonPropertyName("indexingPreset")]
//        public string IndexingPreset { get; set; }

//        [JsonPropertyName("streamingPreset")]
//        public string StreamingPreset { get; set; }

//        [JsonPropertyName("linguisticModelId")]
//        public Guid LinguisticModelId { get; set; }

//        [JsonPropertyName("personModelId")]
//        public Guid PersonModelId { get; set; }

//        [JsonPropertyName("logoGroupId")]
//        public object LogoGroupId { get; set; }

//        [JsonPropertyName("isAdult")]
//        public bool IsAdult { get; set; }

//        [JsonPropertyName("excludedAIs")]
//        public object[] ExcludedAIs { get; set; }

//        [JsonPropertyName("publishedUrl")]
//        public Uri PublishedUrl { get; set; }

//        [JsonPropertyName("publishedProxyUrl")]
//        public object PublishedProxyUrl { get; set; }

//        [JsonPropertyName("viewToken")]
//        public string ViewToken { get; set; }
//    }

//    public partial class Insights
//    {
//        [JsonPropertyName("version")]
//        public string Version { get; set; }

//        [JsonPropertyName("duration")]
//        public string Duration { get; set; }

//        [JsonPropertyName("sourceLanguage")]
//        public Language SourceLanguage { get; set; }

//        [JsonPropertyName("sourceLanguages")]
//        public Language[] SourceLanguages { get; set; }

//        [JsonPropertyName("language")]
//        public Language Language { get; set; }

//        [JsonPropertyName("languages")]
//        public Language[] Languages { get; set; }

//        [JsonPropertyName("transcript")]
//        public Keyword[] Transcript { get; set; }

//        [JsonPropertyName("ocr")]
//        public Ocr[] Ocr { get; set; }

//        [JsonPropertyName("keywords")]
//        public Keyword[] Keywords { get; set; }

//        [JsonPropertyName("topics")]
//        public Topic[] Topics { get; set; }

//        [JsonPropertyName("labels")]
//        public Label[] Labels { get; set; }

//        [JsonPropertyName("scenes")]
//        public Block[] Scenes { get; set; }

//        [JsonPropertyName("shots")]
//        public Shot[] Shots { get; set; }

//        [JsonPropertyName("audioEffects")]
//        public AudioEffect[] AudioEffects { get; set; }

//        [JsonPropertyName("detectedObjects")]
//        public DetectedObject[] DetectedObjects { get; set; }

//        [JsonPropertyName("sentiments")]
//        public Sentiment[] Sentiments { get; set; }

//        [JsonPropertyName("blocks")]
//        public Block[] Blocks { get; set; }

//        [JsonPropertyName("speakers")]
//        public Speaker[] Speakers { get; set; }

//        [JsonPropertyName("textualContentModeration")]
//        public TextualContentModeration TextualContentModeration { get; set; }

//        [JsonPropertyName("statistics")]
//        public Statistics Statistics { get; set; }
//    }

//    public partial class AudioEffect
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("type")]
//        public string Type { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class Instance
//    {
//        [JsonPropertyName("confidence", NullValueHandling = NullValueHandling.Ignore)]
//        public double? Confidence { get; set; }

//        [JsonPropertyName("adjustedStart")]
//        public string AdjustedStart { get; set; }

//        [JsonPropertyName("adjustedEnd")]
//        public string AdjustedEnd { get; set; }

//        [JsonPropertyName("start")]
//        public string Start { get; set; }

//        [JsonPropertyName("end")]
//        public string End { get; set; }

//        [JsonPropertyName("thumbnailId", NullValueHandling = NullValueHandling.Ignore)]
//        public Guid? ThumbnailId { get; set; }
//    }

//    public partial class Block
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class DetectedObject
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("type")]
//        public string Type { get; set; }

//        [JsonPropertyName("thumbnailId")]
//        public Guid ThumbnailId { get; set; }

//        [JsonPropertyName("displayName")]
//        public string DisplayName { get; set; }

//        [JsonPropertyName("wikiDataId")]
//        public string WikiDataId { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class Keyword
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("text")]
//        public string Text { get; set; }

//        [JsonPropertyName("confidence")]
//        public double Confidence { get; set; }

//        [JsonPropertyName("language")]
//        public Language Language { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }

//        [JsonPropertyName("speakerId", NullValueHandling = NullValueHandling.Ignore)]
//        public long? SpeakerId { get; set; }
//    }

//    public partial class Label
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("name")]
//        public string Name { get; set; }

//        [JsonPropertyName("language")]
//        public Language Language { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }

//        [JsonPropertyName("referenceId", NullValueHandling = NullValueHandling.Ignore)]
//        public string ReferenceId { get; set; }
//    }

//    public partial class Ocr
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("text")]
//        public string Text { get; set; }

//        [JsonPropertyName("confidence")]
//        public double Confidence { get; set; }

//        [JsonPropertyName("left")]
//        public long Left { get; set; }

//        [JsonPropertyName("top")]
//        public long Top { get; set; }

//        [JsonPropertyName("width")]
//        public long Width { get; set; }

//        [JsonPropertyName("height")]
//        public long Height { get; set; }

//        [JsonPropertyName("angle")]
//        public long Angle { get; set; }

//        [JsonPropertyName("language")]
//        public Language Language { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class Sentiment
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("averageScore")]
//        public double AverageScore { get; set; }

//        [JsonPropertyName("sentimentType")]
//        public string SentimentType { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class Shot
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("keyFrames")]
//        public Block[] KeyFrames { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }

//        [JsonPropertyName("tags", NullValueHandling = NullValueHandling.Ignore)]
//        public string[] Tags { get; set; }
//    }

//    public partial class Speaker
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("name")]
//        public string Name { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class Statistics
//    {
//        [JsonPropertyName("correspondenceCount")]
//        public long CorrespondenceCount { get; set; }

//        [JsonPropertyName("speakerTalkToListenRatio")]
//        public SpeakerLongestMonologClass SpeakerTalkToListenRatio { get; set; }

//        [JsonPropertyName("speakerLongestMonolog")]
//        public SpeakerLongestMonologClass SpeakerLongestMonolog { get; set; }

//        [JsonPropertyName("speakerNumberOfFragments")]
//        public SpeakerLongestMonologClass SpeakerNumberOfFragments { get; set; }

//        [JsonPropertyName("speakerWordCount")]
//        public SpeakerLongestMonologClass SpeakerWordCount { get; set; }
//    }

//    public partial class SpeakerLongestMonologClass
//    {
//        [JsonPropertyName("1")]
//        public long The1 { get; set; }
//    }

//    public partial class TextualContentModeration
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("bannedWordsCount")]
//        public long BannedWordsCount { get; set; }

//        [JsonPropertyName("bannedWordsRatio")]
//        public long BannedWordsRatio { get; set; }

//        [JsonPropertyName("instances")]
//        public object[] Instances { get; set; }
//    }

//    public partial class Topic
//    {
//        [JsonPropertyName("id")]
//        public long Id { get; set; }

//        [JsonPropertyName("name")]
//        public string Name { get; set; }

//        [JsonPropertyName("referenceId")]
//        public string ReferenceId { get; set; }

//        [JsonPropertyName("referenceType")]
//        public string ReferenceType { get; set; }

//        [JsonPropertyName("iptcName")]
//        public string IptcName { get; set; }

//        [JsonPropertyName("confidence")]
//        public double Confidence { get; set; }

//        [JsonPropertyName("iabName")]
//        public string IabName { get; set; }

//        [JsonPropertyName("language")]
//        public Language Language { get; set; }

//        [JsonPropertyName("instances")]
//        public Instance[] Instances { get; set; }
//    }

//    public partial class VideosRange
//    {
//        [JsonPropertyName("videoId")]
//        public string VideoId { get; set; }

//        [JsonPropertyName("range")]
//        public Range Range { get; set; }
//    }

//    public partial class Range
//    {
//        [JsonPropertyName("start")]
//        public string Start { get; set; }

//        [JsonPropertyName("end")]
//        public string End { get; set; }
//    }

//    public enum Language { EnUs, EsEs, LtLt, ToTo };

//    //public partial class VideoIndexerResultClass
//    //{
//    //    public static VideoIndexerResultClass FromJson(string json) => JsonConvert.DeserializeObject<VideoIndexerResultClass>(json, hello_rusy.Converter.Settings);
//    //}

//    //public static class Serialize
//    //{
//    //    public static string ToJson(this VideoIndexerResultClass self) => JsonConvert.SerializeObject(self, hello_rusy.Converter.Settings);
//    //}

//    //internal static class Converter
//    //{
//    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
//    //    {
//    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
//    //        DateParseHandling = DateParseHandling.None,
//    //        Converters =
//    //        {
//    //            LanguageConverter.Singleton,
//    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
//    //        },
//    //    };
//    //}

//    //internal class LanguageConverter : JsonConverter
//    //{
//    //    public override bool CanConvert(Type t) => t == typeof(Language) || t == typeof(Language?);

//    //    public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
//    //    {
//    //        if (reader.TokenType == JsonToken.Null) return null;
//    //        var value = serializer.Deserialize<string>(reader);
//    //        switch (value)
//    //        {
//    //            case "en-US":
//    //                return Language.EnUs;
//    //            case "es-ES":
//    //                return Language.EsEs;
//    //            case "lt-LT":
//    //                return Language.LtLt;
//    //            case "to-TO":
//    //                return Language.ToTo;
//    //        }
//    //        throw new Exception("Cannot unmarshal type Language");
//    //    }

//    //    public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
//    //    {
//    //        if (untypedValue == null)
//    //        {
//    //            serializer.Serialize(writer, null);
//    //            return;
//    //        }
//    //        var value = (Language)untypedValue;
//    //        switch (value)
//    //        {
//    //            case Language.EnUs:
//    //                serializer.Serialize(writer, "en-US");
//    //                return;
//    //            case Language.EsEs:
//    //                serializer.Serialize(writer, "es-ES");
//    //                return;
//    //            case Language.LtLt:
//    //                serializer.Serialize(writer, "lt-LT");
//    //                return;
//    //            case Language.ToTo:
//    //                serializer.Serialize(writer, "to-TO");
//    //                return;
//    //        }
//    //        throw new Exception("Cannot marshal type Language");
//    //    }

//    //    public static readonly LanguageConverter Singleton = new LanguageConverter();
//   }

